/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlythuvien.view;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import quanlythuvien.Bao;
import quanlythuvien.Dao.thuvienDao;
import quanlythuvien.Tapchi;
import quanlythuvien.sach;
import quanlythuvien.service.thuvienService;

/**
 *
 * @author Dell
 */
public class ListthuvienFrame extends javax.swing.JFrame {
    thuvienService thuvienservice ;
    thuvienService thuvienservice1;
    thuvienService thuvienservice2;
    DefaultTableModel defaultTableModel;
    DefaultTableModel defaultTableModel2;
    DefaultTableModel defaultTableModel3;
    thuvienDao dao = new thuvienDao();
    String strfind="";
    /**
     * Creates new form ListthuvienFrame
     */
    public ListthuvienFrame() throws SQLException {
        initComponents();
        thuvienservice = new thuvienService();
        defaultTableModel = new DefaultTableModel();
        sachTable.setModel(defaultTableModel);
        defaultTableModel.addColumn("IDtailieu");
        defaultTableModel.addColumn("Tennxs");
        defaultTableModel.addColumn("Tentacgia");
        defaultTableModel.addColumn("Sotrang");
        defaultTableModel.addColumn("Sobanphathanh");
        List<sach> items = thuvienservice.getALLItems1();
        for(sach item2 : items ){
        defaultTableModel.addRow(new Object[]{item2.getIDtailieu(),item2.getTennxs(),item2.getTentacgia(), item2.getSotrang(),item2.getSobanphathanh()});   
        
        }
        
        thuvienservice1 = new thuvienService();
        defaultTableModel2 = new DefaultTableModel();
        tapchiTable.setModel(defaultTableModel2);
        defaultTableModel2.addColumn("IDtailieu");
        defaultTableModel2.addColumn("Tennxs");
        defaultTableModel2.addColumn("IdPH");
        defaultTableModel2.addColumn("Thangphathanh");
        defaultTableModel2.addColumn("Sobanphathanh");
        List<Tapchi> items1 = thuvienservice1.getALLItems2();
        for(Tapchi item3 : items1 ){
        defaultTableModel2.addRow(new Object[]{item3.getIDtailieu(),item3.getTennxs(),item3.getIdPH(), item3.getThangphathanh(),item3.getSobanphathanh()});
        }
        
        
        thuvienservice2 = new thuvienService();
        defaultTableModel3 = new DefaultTableModel();
        baoTable.setModel(defaultTableModel3);
        defaultTableModel3.addColumn("IDtailieu");
        defaultTableModel3.addColumn("Tennxs");
        
        defaultTableModel3.addColumn("Ngayphathanh");
        defaultTableModel3.addColumn("Sobanphathanh");
        List<Bao> items2 = thuvienservice1.getALLItems3();
        for(Bao item4 : items2 ){
        defaultTableModel3.addRow(new Object[]{item4.getIDtailieu(),item4.getTennxs(), item4.getNgayphathanh(),item4.getSobanphathanh()});
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        sachTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tapchiTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        baoTable = new javax.swing.JTable();
        addButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        xoaButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        xoatapchiButton = new javax.swing.JButton();
        baoButton = new javax.swing.JButton();
        timkiemsachButton = new javax.swing.JButton();
        timkiemsachTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sachTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        sachTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(sachTable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("sách");

        tapchiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tapchiTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tapchiTable);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("tapchi");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("Bao");

        baoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        baoTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(baoTable);

        addButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addButton.setText("Thêm mới sách");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("thêm mới tap chi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("thêm mới báo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        xoaButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        xoaButton.setText("xoa sach");
        xoaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaButtonActionPerformed(evt);
            }
        });

        refreshButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        refreshButton.setText("refresh sach");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("refresh tapchi");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("refresh bao");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        xoatapchiButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        xoatapchiButton.setText("xoa tapchi");
        xoatapchiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoatapchiButtonActionPerformed(evt);
            }
        });

        baoButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        baoButton.setText("xoa báo");
        baoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baoButtonActionPerformed(evt);
            }
        });

        timkiemsachButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        timkiemsachButton.setText("tim kiếm sách");
        timkiemsachButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timkiemsachButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xoaButton)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(230, 230, 230))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(baoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addButton)
                    .addComponent(timkiemsachTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(timkiemsachButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(refreshButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(xoatapchiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(30, 30, 30)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(baoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5)
                    .addComponent(xoaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(xoatapchiButton)
                        .addComponent(jButton4)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timkiemsachButton)
                    .addComponent(timkiemsachTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(169, 169, 169))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        new addThuvien().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new addtapchi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new addbao().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void xoaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaButtonActionPerformed
        // TODO add your handling code here:
        int row = sachTable.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(ListthuvienFrame.this, "vui long chon du lieu truoc","Loi",JOptionPane.ERROR_MESSAGE);
        }else{
        int confirm = JOptionPane.showConfirmDialog(ListthuvienFrame.this, "ban chac chan muon xoa khong?");
        if(confirm==JOptionPane.YES_OPTION){
            int sachid = Integer.valueOf(String.valueOf(sachTable.getValueAt(row, 0)));
            
            try {
                thuvienservice.xoadulieu(sachid);
            } catch (SQLException ex) {
                Logger.getLogger(ListthuvienFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        defaultTableModel.setRowCount(0);
        List<sach> items = null;
        try {
            items = thuvienservice.getALLItems1();
        } catch (SQLException ex) {
            Logger.getLogger(ListthuvienFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for(sach item2 : items ){
        defaultTableModel.addRow(new Object[]{item2.getIDtailieu(),item2.getTennxs(),item2.getTentacgia(), item2.getSotrang(),item2.getSobanphathanh()});     
        }               
        }
        }
    }//GEN-LAST:event_xoaButtonActionPerformed

  
    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        defaultTableModel.setRowCount(0);
        List<sach> items = null;
        try {
            items = thuvienservice.getALLItems1();
        } catch (SQLException ex) {
            Logger.getLogger(ListthuvienFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for(sach item2 : items ){
        defaultTableModel.addRow(new Object[]{item2.getIDtailieu(),item2.getTennxs(),item2.getTentacgia(), item2.getSotrang(),item2.getSobanphathanh()});     
    }//GEN-LAST:event_refreshButtonActionPerformed
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        defaultTableModel2.setRowCount(0);
         List<Tapchi> items1 = null;
        try {
            items1 = thuvienservice1.getALLItems2();
        } catch (SQLException ex) {
            Logger.getLogger(ListthuvienFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(Tapchi item3 : items1 ){
        defaultTableModel2.addRow(new Object[]{item3.getIDtailieu(),item3.getTennxs(),item3.getIdPH(), item3.getThangphathanh(),item3.getSobanphathanh()});
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        defaultTableModel3.setRowCount(0);
        List<Bao> items2 = null;
        try {
            items2 = thuvienservice1.getALLItems3();
        } catch (SQLException ex) {
            Logger.getLogger(ListthuvienFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(Bao item4 : items2 ){
        defaultTableModel3.addRow(new Object[]{item4.getIDtailieu(),item4.getTennxs(), item4.getNgayphathanh(),item4.getSobanphathanh()});
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void xoatapchiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoatapchiButtonActionPerformed
        // TODO add your handling code here:
        int row = tapchiTable.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(ListthuvienFrame.this, "vui long chon du lieu truoc","Loi",JOptionPane.ERROR_MESSAGE);
        }else{
        int confirm = JOptionPane.showConfirmDialog(ListthuvienFrame.this, "ban chac chan muon xoa khong?");
        if(confirm==JOptionPane.YES_OPTION){
            int tapchiid = Integer.valueOf(String.valueOf(tapchiTable.getValueAt(row, 0)));
            
            try {
                thuvienservice.xoadulieu(tapchiid);
            } catch (SQLException ex) {
                Logger.getLogger(ListthuvienFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        defaultTableModel2.setRowCount(0);
         List<Tapchi> items1 = null;
        try {
            items1 = thuvienservice1.getALLItems2();
        } catch (SQLException ex) {
            Logger.getLogger(ListthuvienFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(Tapchi item3 : items1 ){
        defaultTableModel2.addRow(new Object[]{item3.getIDtailieu(),item3.getTennxs(),item3.getIdPH(), item3.getThangphathanh(),item3.getSobanphathanh()});
        }             
        }
        }
    }//GEN-LAST:event_xoatapchiButtonActionPerformed

    private void baoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baoButtonActionPerformed
        // TODO add your handling code here:
        int row = baoTable.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(ListthuvienFrame.this, "vui long chon du lieu truoc","Loi",JOptionPane.ERROR_MESSAGE);
        }else{
        int confirm = JOptionPane.showConfirmDialog(ListthuvienFrame.this, "ban chac chan muon xoa khong?");
        if(confirm==JOptionPane.YES_OPTION){
            int baoid = Integer.valueOf(String.valueOf(baoTable.getValueAt(row, 0)));
            
            try {
                thuvienservice.xoadulieu(baoid);
            } catch (SQLException ex) {
                Logger.getLogger(ListthuvienFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        defaultTableModel3.setRowCount(0);
        List<Bao> items2 = null;
        try {
            items2 = thuvienservice1.getALLItems3();
        } catch (SQLException ex) {
            Logger.getLogger(ListthuvienFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(Bao item4 : items2 ){
        defaultTableModel3.addRow(new Object[]{item4.getIDtailieu(),item4.getTennxs(), item4.getNgayphathanh(),item4.getSobanphathanh()});
        }          
        }
        }
    }//GEN-LAST:event_baoButtonActionPerformed
   public void fillTable1() throws SQLException{
    DefaultTableModel tbModel = (DefaultTableModel) sachTable.getModel();
    tbModel.setRowCount(0);
    for(sach Sach : dao.timkiemsach(strfind) ){
       Object dataRow[] = new Object[5];
       dataRow[0]=Sach.getIDtailieu();
       dataRow[1]=Sach.getTennxs();
       dataRow[2]=Sach.getLoai();
       dataRow[3]=Sach.getTentacgia();
       dataRow[4]=Sach.getSotrang();
       tbModel.addRow(dataRow);
    
    }
   
   
   }
    
    private void timkiemsachButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timkiemsachButtonActionPerformed
        strfind=timkiemsachTextField.getText();
        try {
            // TODO add your handling code here:
            fillTable1();
        } catch (SQLException ex) {
            Logger.getLogger(ListthuvienFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_timkiemsachButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListthuvienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListthuvienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListthuvienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListthuvienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ListthuvienFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ListthuvienFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton baoButton;
    private javax.swing.JTable baoTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTable sachTable;
    private javax.swing.JTable tapchiTable;
    private javax.swing.JButton timkiemsachButton;
    private javax.swing.JTextField timkiemsachTextField;
    private javax.swing.JButton xoaButton;
    private javax.swing.JButton xoatapchiButton;
    // End of variables declaration//GEN-END:variables

   
}
